services:
  - type: web
    name: vladimir-smirnov-news-website-golang
    runtime: go
    repo: https://github.com/vladimir-smirnov-fin/news-website-golang
    plan: free
    buildCommand: go build -o main
    startCommand: ./main
    envVars:
      - key: PORT
        value: 8080
      # DATABASE_URL will be added manually in Render dashboard, not in this file
      # neon.tech (PostgreSQL database)